### ISSUE TITLE
Error while installing with poetry install

### ISSUE THREAD

**Issue by Arataks** [portmind/armenian-ocr#4]
[error.log](https://github.com/user-attachments/files/16921175/error.log)

**Comment by v4nn4** [comment]
Using a 3.11 environment worked for me (macOS). Here is my TOML file:

```toml
[tool.poetry]
name = "armenian-ocr"
version = "0.1.0"
description = "OCR implementation for Armenian documents"
authors = ["Portmind's Team"]
maintainers = [
    "Khachatur Khechoyan <khachatur.khechoyan@portmind.com>",
    "Sevak Harutyunyan <sevak.harutyunyan@portmind.com>",
    "Sipan Muradyan <sipan.muradyan@portmind.com>",
]

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.5.1"
torchvision = "^0.20.1"
pdf2image = "^1.17.0"
pandas = "^2.2.3"
opencv-python = "^4.11.0.86"
scipy = "^1.15.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```
